### ISSUE TITLE
Could not find gem 'docx-converter' in any of the gem sources listed in your Gemfile.

### ISSUE THREAD

**Issue by echan00** [michaelfranzl/docx_converter#4]
Tried to install this gem but wasn't able to find it..

`Could not find gem 'docx-converter' in any of the gem sources listed in your Gemfile.`

**Comment by michaelfranzl** [comment]
Closing since this is not a problem with this repository.

You have a typo. Change the dash to an underscore. See: https://rubygems.org/gems/docx_converter
